export default {
  SET_LIST_PASIEN: (state, data) => {
    state.listKasus = data
  },
  RESET_LIST_CASE: (state) => {
    state.listKasus = []
  },
  SET_TOTAL_LIST_PASIEN: (state, data) => {
    state.totalList = data
  },
  SET_TOTAL_DATA_PASIEN: (state, data) => {
    state.totalData = data
  },
  SET_TOTAL_PENDING: (state, data) => {
    state.totalPending = data
  },
  RESET_FORM_PASIEN: (state) => {
    state.formPasien.nik = ''
    state.formPasien.name = ''
    state.formPasien.birth_date = ''
    state.formPasien.is_nik_exists = false
    state.formPasien.is_phone_number_exists = false
    state.formPasien.is_went_abroad = false
    state.formPasien.is_went_other_city = false
    state.formPasien.is_contact_with_positive = false
    state.formPasien.age = ''
    state.formPasien.month = ''
    state.formPasien.occupation = ''
    state.formPasien.gender = ''
    state.formPasien.nationality = ''
    state.formPasien.nationality_name = ''
    state.formPasien.id_case_national = ''
    state.formPasien.id_case_related = ''
    state.formPasien.phone_number = ''
    state.formPasien.office_address = ''
    state.formPasien.address_street = ''
    state.formPasien.address_district_code = ''
    state.formPasien.address_district_name = ''
    state.formPasien.address_subdistrict_code = ''
    state.formPasien.address_subdistrict_name = ''
    state.formPasien.address_village_code = ''
    state.formPasien.address_village_name = ''
    state.formPasien.status = ''
    state.formPasien.stage = ''
    state.formPasien.first_symptom_date = ''
    state.formPasien.diagnosis = []
    state.formPasien.history_tracing = []
    state.formPasien.history_notes = ''
    state.formPasien.current_location_type = ''
    state.formPasien.current_location_address = ''
    state.formPasien.current_location_district_code = ''
    state.formPasien.current_location_subdistrict_code = ''
    state.formPasien.current_location_village_code = ''
    state.formPasien.interviewers_name = ''
    state.formPasien.interviewers_phone_number = ''
    state.formPasien.interview_date = ''
    state.formPasien.rt = ''
    state.formPasien.rw = ''
    state.formPasien.name_parents = ''
    state.formPasien.note_nik = ''
    state.formPasien.note_phone_number = ''
    state.formPasien.place_of_birth = ''
    state.formPasien.diagnosis_ards = 2
    state.formPasien.diagnosis_covid = 2
    state.formPasien.diagnosis_pneumonia = 2
    state.formPasien.other_diagnosis = ''
    state.formPasien.serum_check = false
    state.formPasien.sputum_check = false
    state.formPasien.swab_check = false
    state.formPasien.physical_check = ''
    state.formPasien.pysichal_activity = ''
    state.formPasien.smoking = 2
    state.formPasien.consume_alcohol = 2
    state.formPasien.income = ''
    state.formPasien.travel = ''
    state.formPasien.visited = ''
    state.formPasien.start_travel = ''
    state.formPasien.end_travel = ''
    state.formPasien.close_contact = 2
    state.formPasien.close_contact_confirm = 2
    state.formPasien.close_contact_animal_market = 2
    state.formPasien.close_contact_public_place = 2
    state.formPasien.close_contact_medical_facility = 2
    state.formPasien.close_contact_heavy_ispa_group = null
    state.formPasien.close_contact_health_worker = false
    state.formPasien.apd_use = []
    state.formPasien.close_contact_premier = []
    state.formPasien.inspection_support = []
    state.formPasien.is_other_diagnosisr_respiratory_disease = false
    state.formPasien.travelling_history = []
    state.formPasien.has_visited_public_place = false
    state.formPasien.visited_public_place = []
    state.formPasien.visited_local_area_before_sick_14_days = false
    state.formPasien.visited_local_area = []
    state.formPasien.other_diagnosisr_respiratory_disease = ''
    state.formPasien.name_close_contact = ''
    state.formPasien.id_close_contact = ''
    state.formPasien.name_close_contact_confirm = ''
    state.formPasien.id_close_contact_confirm = ''
    state.formPasien.close_contact_patient = []
    state.formPasien.physical_check_temperature = ''
    state.formPasien.physical_check_blood_pressure = ''
    state.formPasien.physical_check_pulse = ''
    state.formPasien.physical_check_respiration = ''
    state.formPasien.physical_check_height = ''
    state.formPasien.physical_check_weight = ''
    state.formPasien.contact_date = ''
    state.formPasien.animal_market_date = ''
    state.formPasien.animal_market_other = ''
    state.formPasien.public_place_date = ''
    state.formPasien.public_place_other = ''
    state.formPasien.medical_facility_date = ''
    state.formPasien.medical_facility_other = ''
    state.formPasien.health_workers = ''
    state.formPasien.yearsOld = ''
    state.formPasien.monthsOld = ''
  },
  RESET_RIWAYAT_FORM_PASIEN: (state) => {
    state.formRiwayatPasien.case = ''
    state.formRiwayatPasien.status = ''
    state.formRiwayatPasien.stage = ''
    state.formRiwayatPasien.diagnosis = []
    state.formRiwayatPasien.history_tracing = []
    state.formRiwayatPasien.first_symptom_date = ''
    state.formRiwayatPasien.history_notes = ''
    state.formRiwayatPasien.current_location_type = ''
    state.formRiwayatPasien.current_location_address = ''
    state.formRiwayatPasien.current_location_district_code = ''
    state.formRiwayatPasien.current_location_subdistrict_code = ''
    state.formRiwayatPasien.current_location_village_code = ''
  }
}
