import actions from './actions'
import mutations from './mutations'
import getters from './getters'

const state = {
  totalList: 0,
  totalDataRDT: 0,
  listRDT: [],
  listTarget: [],
  formHistoryTest: {
    address_detail: '',
    address_district_code: '',
    address_district_name: '',
    address_subdistrict_code: '',
    address_subdistrict_name: '',
    address_village_code: '',
    address_village_name: '',
    age: '',
    author_district_code: '',
    author_district_name: '',
    birth_date: null,
    category: null,
    code_test: '',
    code_tool_tester: '',
    createdAt: '',
    final_result: '',
    gender: '',
    id_case: '',
    lab: '',
    last_history: '',
    mechanism: null,
    name: '',
    nationality: '',
    nationality_name: '',
    nik: '',
    note_nik: '',
    note_phone_number: '',
    pcr_count: null,
    phone_number: '',
    rdt_count: null,
    rdt_to: null,
    sampling_type: null,
    source_data: '',
    status: null,
    swab_to: null,
    target: '',
    test_address_detail: '',
    test_address_district_code: '',
    test_address_district_name: '',
    test_address_subdistrict_code: '',
    test_address_subdistrict_name: '',
    test_address_village_code: '',
    test_address_village_name: '',
    test_date: '',
    test_location: '',
    test_location_type: '',
    test_method: null,
    test_note: null,
    test_other_location: '',
    tool_tester: ''
  }
}

export default {
  namespaced: true,
  state,
  getters,
  actions,
  mutations
}
